### ISSUE TITLE
Problem in getting the crash analytics

### ISSUE THREAD

**Issue by farazhere** [andrehtissot/cordova-plugin-firebase-crash-report#1]
I added the cordova-plugin-firebase-crash-report plugin and also placed google-services.json file in the root as well as project folder.
Then built the app but nothing shows in my firebase console.
Can you please confirm me the basic steps to adding the crash reporting to my app, i did like this:
Added a proejct in Firebase console
Added an app with the id i have in my config.xml
Added the cordova-plugin-firebase-crash-report plugin 
Downloaded the google-services.json file after setting up for android in firebase console and placed in all likely locations
Built for android

**Comment by andrehtissot** [comment]
If it built, it should have found the `google-services.json`.


Try to execute inside your app:
```Javascript
FirebaseCrashReport.log("Crash test", function(){
    alert('FirebaseCrashReport Worked!');
}, function(err){
    alert('FirebaseCrashReport Failed: '+err);
});
```
If the alert message is `FirebaseCrashReport Failed`, write here the error message returned.
If the alert message is `FirebaseCrashReport Worked!`, the message `Crash test` should appear in your Firebase Console. If it doesn't appear, please check in the Android `adb logcat` for error messages.
